// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDFLo7CvSssfV7RkpGGz6r7eONaed7hh0o",
      authDomain: "virtusa-22e17.firebaseapp.com",
      projectId: "virtusa-22e17",
      storageBucket: "virtusa-22e17.appspot.com",
      messagingSenderId: "434872887896",
      appId: "1:434872887896:web:7a9db6f1355518355fb82d",
      measurementId: "G-F51NFQ5L8R"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuLbnvc_6NRo0_oFR5NFJHl609c8Z82Mc',
    appId: '1:434872887896:android:3cd1a00c256532835fb82d',
    messagingSenderId: '434872887896',
    projectId: 'virtusa-22e17',
    storageBucket: 'virtusa-22e17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAh6XtUImotyDzIfBfgRCtgWBJW6OPwZE',
    appId: '1:1067774015225:ios:70437bdc29aab0d6965428',
    messagingSenderId: '1067774015225',
    projectId: 'sign-in-tutorial-c86bd',
    storageBucket: 'sign-in-tutorial-c86bd.appspot.com',
    iosClientId: '1067774015225-40d5npqo3g6os0cjf8i43la7ugk7bjjn.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSign',
  );
}
